//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSPortal.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class soletech {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal soletech() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESSPortal.App_GlobalResources.soletech", typeof(soletech).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string Arabic_Name {
            get {
                return ResourceManager.GetString("Arabic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benifits.
        /// </summary>
        public static string Benifits {
            get {
                return ResourceManager.GetString("Benifits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string Contact_Information {
            get {
                return ResourceManager.GetString("Contact_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents.
        /// </summary>
        public static string Dependents {
            get {
                return ResourceManager.GetString("Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string English_Name {
            get {
                return ResourceManager.GetString("English_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        public static string Job_Details {
            get {
                return ResourceManager.GetString("Job_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        public static string Job_ID {
            get {
                return ResourceManager.GetString("Job_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string Job_Type {
            get {
                return ResourceManager.GetString("Job_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string Joining_Date {
            get {
                return ResourceManager.GetString("Joining_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loaned Item.
        /// </summary>
        public static string loaned_Item {
            get {
                return ResourceManager.GetString("loaned_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Insurance.
        /// </summary>
        public static string Medical_Insurance {
            get {
                return ResourceManager.GetString("Medical_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string More_Details {
            get {
                return ResourceManager.GetString("More_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Payslip.
        /// </summary>
        public static string More_Payslip {
            get {
                return ResourceManager.GetString("More_Payslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Skills.
        /// </summary>
        public static string More_Skills {
            get {
                return ResourceManager.GetString("More_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Absence Request.
        /// </summary>
        public static string My_Absence_Request {
            get {
                return ResourceManager.GetString("My_Absence_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my business trip.
        /// </summary>
        public static string my_business_trip {
            get {
                return ResourceManager.GetString("my_business_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My EOS Request.
        /// </summary>
        public static string My_EOS_Request {
            get {
                return ResourceManager.GetString("My_EOS_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Excuse Request.
        /// </summary>
        public static string My_Excuse_Request {
            get {
                return ResourceManager.GetString("My_Excuse_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Genera Request.
        /// </summary>
        public static string My_General_Request {
            get {
                return ResourceManager.GetString("My_General_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Information.
        /// </summary>
        public static string My_Information {
            get {
                return ResourceManager.GetString("My_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my Leave.
        /// </summary>
        public static string my_Leave {
            get {
                return ResourceManager.GetString("my_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Letters Request.
        /// </summary>
        public static string My_Letters_Request {
            get {
                return ResourceManager.GetString("My_Letters_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recruitment Request.
        /// </summary>
        public static string My_Recruitment_Request {
            get {
                return ResourceManager.GetString("My_Recruitment_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My request Loan.
        /// </summary>
        public static string My_request_Loan {
            get {
                return ResourceManager.GetString("My_request_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Training Request.
        /// </summary>
        public static string My_Training_Request {
            get {
                return ResourceManager.GetString("My_Training_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Number.
        /// </summary>
        public static string Personal_Number {
            get {
                return ResourceManager.GetString("Personal_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Description.
        /// </summary>
        public static string Position_Description {
            get {
                return ResourceManager.GetString("Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position ID.
        /// </summary>
        public static string Position_ID {
            get {
                return ResourceManager.GetString("Position_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Enchancment.
        /// </summary>
        public static string Ticket_Enchancment {
            get {
                return ResourceManager.GetString("Ticket_Enchancment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Request.
        /// </summary>
        public static string Ticket_Request {
            get {
                return ResourceManager.GetString("Ticket_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total skills.
        /// </summary>
        public static string Total_skills {
            get {
                return ResourceManager.GetString("Total_skills", resourceCulture);
            }
        }
    }
}
